### ISSUE TITLE
Discord vencord.

### ISSUE THREAD

**Issue by Xoui** [delusionzz/Emerald-old#1]
Hello, this is not really an issue but an question. So I have tryed to implement the vencord uv.config.js from your fork of uv from the discord server. I have my own proxy called imagine node. Its a wip, But it would not work went i copied the code for uv it just simply did not work. Can you help me please?

**Comment by illusionTBA** [comment]
This is definitely not the right repo to make an issue on that, but give me your discord and we can discuss this further
